quadruped:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
  tail:
    yaw_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_tail_yaw
      pid: {p: 200.0, i: 1.0, d: 10.0}
    pitch_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_tail_pitch
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_fr:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip_fr
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_fr
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_ankle_fr
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_fl:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip_fl
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_fl
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_ankle_fl
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_br:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip_br
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_br
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_ankle_br
      pid: {p: 200.0, i: 1.0, d: 10.0}
  leg_bl:
    hip_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_hip_bl
      pid: {p: 200.0, i: 1.0, d: 10.0}
    knee_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_knee_bl
      pid: {p: 200.0, i: 1.0, d: 10.0}
    ankle_joint_position_controller:
      type: effort_controllers/JointPositionController
      joint: joint_ankle_bl
      pid: {p: 200.0, i: 1.0, d: 10.0}